# Generated by Django 2.2.1 on 2019-05-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='fotos',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='pais',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='provincia',
            field=models.CharField(max_length=20),
        ),
    ]
