# Generated by Django 2.2.1 on 2019-05-17 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0002_auto_20190512_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('monto_puja', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='semana',
            name='fecha_fin_sem',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 17)),
        ),
        migrations.AddField(
            model_name='semana',
            name='fecha_inicio_sem',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 17)),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fotos',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='semana',
            name='costo',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='numero_semana',
            field=models.IntegerField(blank=True, default=datetime.date(2019, 5, 17)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_fin',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 17)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
