# Generated by Django 2.2.1 on 2019-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0003_auto_20190517_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='fecha_fin_sem',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='fecha_inicio_sem',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='monto_base',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='numero_semana',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
    ]
