# Generated by Django 2.2.1 on 2019-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0004_auto_20190517_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeSwitchHome.Propiedad'),
        ),
    ]
