# Generated by Django 2.2.1 on 2019-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0006_auto_20190518_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='subastada',
            field=models.BooleanField(default=False),
        ),
    ]
