# Generated by Django 2.2.1 on 2019-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0007_propiedad_subastada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='subastada',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='subastas_activas',
            field=models.IntegerField(default=0),
        ),
    ]
