# Generated by Django 2.2.1 on 2019-05-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0009_auto_20190518_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='subasta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeSwitchHome.Subasta'),
        ),
    ]
