# Generated by Django 2.2.1 on 2019-05-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0010_auto_20190518_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='fotos',
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, upload_to='')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeSwitchHome.Propiedad')),
            ],
        ),
    ]
