# Generated by Django 2.2.1 on 2019-05-19 20:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0012_auto_20190518_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='postor',
            name='fecha_puja',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postor',
            name='subasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeSwitchHome.Subasta'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='postor',
            order_with_respect_to='fecha_puja',
        ),
    ]
