# Generated by Django 2.2.1 on 2019-05-20 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0013_auto_20190519_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postor',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeSwitchHome.Subasta'),
        ),
    ]
