# Generated by Django 2.2.1 on 2019-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0015_auto_20190520_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
