# Generated by Django 2.2.1 on 2019-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0017_propiedad_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='propiedad',
            unique_together={('titulo', 'localidad')},
        ),
    ]
