# Generated by Django 2.2.1 on 2019-06-20 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0020_auto_20190620_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
