# Generated by Django 2.2.1 on 2019-06-21 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0021_auto_20190620_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
