# Generated by Django 2.2.1 on 2019-06-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0022_semana_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subasta',
            old_name='fecha_fin',
            new_name='fecha_inicio_sem',
        ),
    ]
