# Generated by Django 2.2.1 on 2019-07-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0023_auto_20190621_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semana',
            name='habilitada',
        ),
        migrations.AddField(
            model_name='semana',
            name='habilitada_hotsale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semana',
            name='habilitada_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semana',
            name='habilitada_subasta',
            field=models.BooleanField(default=False),
        ),
    ]
