# Generated by Django 2.2.1 on 2019-07-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0024_auto_20190710_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='reservada_desde',
            field=models.CharField(choices=[('DIRECTA', 'DIRECTA'), ('SUBASTA', 'SUBASTA'), ('HOTSALE', 'HOTSALE')], default=None, max_length=15),
            preserve_default=False,
        ),
    ]
