# Generated by Django 2.2.1 on 2019-07-12 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomeSwitchHome', '0025_auto_20190710_2331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postor',
            unique_together={('usuario', 'fecha_puja', 'subasta')},
        ),
    ]
