# Generated by Django 2.2.1 on 2019-07-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0026_auto_20190712_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postor',
            unique_together=set(),
        ),
    ]
