# Generated by Django 2.2.1 on 2019-07-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0031_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='semana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeSwitchHome.Semana'),
        ),
    ]
