# Generated by Django 2.2.1 on 2019-07-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0033_historialres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialRes',
        ),
    ]
