# Generated by Django 2.2.1 on 2019-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0035_reserva_titulo_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='titulo_prop',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
