# Generated by Django 2.2.1 on 2019-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSwitchHome', '0036_auto_20190715_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='titulo_prop',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
